drone/go-convert

- convert/harness/downgrader/downgrade.go
- go.mod
- go.sum
- pipeline was missing from the returned yaml
- Spec field was being assigned directly to a pointer to the v0.StepPlugin type, which caused the type assertion error.
> (bug) fixes a few issues with downgrading from new harness to old harness yaml

- convert/gitlab/convert.go
- convert/gitlab/testdata/templates/allow_failure.yaml.golden
- convert/gitlab/testdata/templates/exit_codes.yaml.golden
- convert/gitlab/testdata/templates/extends.yaml.golden
allow_failure should convert to ignore all error types
> fix: ignore all errors for gitlab conversions

- convert/harness/downgrader/downgrade.go
- convert/harness/downgrader/testdata/stage-conditional.yaml
- convert/harness/downgrader/testdata/stage-conditional.yaml.golden
- convert/harness/downgrader/testdata/step-conditional.yaml
- convert/harness/downgrader/testdata/step-conditional.yaml.golden
<+trigger.branch> will always contain the current branch
<+trigger.targetBranch> will contain the current branch on a push event, but on a pull request event it will contain the target branch for the pull request
> fix: use targetBranch not branch for conditions

- convert/harness/downgrader/downgrade.go
Some steps are not supported by go convert due to which in the generated yaml we get a null value for that step. Added check to avoid this.
> skipping unsupported step for harness downgrader

- convert/jenkinsjson/convertTestFiles/pwsh/Jenkinsfile
- convert/jenkinsjson/convertTestFiles/pwsh/pwsh.yaml
- convert/jenkinsjson/convertTestFiles/pwsh/pwshSnippet.json
- convert/jenkinsjson/covert.go
- convert/jenkinsjson/json/pwsh.go
- convert/jenkinsjson/json/pwsh_test.go
Added "pwsh" support to go-convert specific to jenkins migration.
PWSH Jenkins Trace: [pwsh-test__4.json](https://github.com/user-attachments/files/16837700/pwsh-test__4.json)
Test Output:
```bash
go run main.go jenkinsjson -downgrade pwsh-test__4.json
```
```
pipeline:
identifier: default
name: default
orgIdentifier: default
projectIdentifier: default
properties:
ci:
codebase:
build: <+input>
stages:
- stage:
identifier: build
name: build
spec:
cloneCodebase: true
execution:
steps:
- stepGroup:
identifier: Stage__nullebf434
name: example
steps:
- step:
identifier: pwsh48add0
name: pwsh
spec:
command: Write-Output "Hello from powershell"
image: mcr.microsoft.com/powershell
shell: Pwsh
timeout: ""
type: Run
timeout: ""
platform:
arch: Amd64
os: Linux
runtime:
spec: {}
type: Cloud
type: CI …
```
> feat: [CI-14066]: Jenkins pwsh function

- convert/jenkinsjson/convert.go
- convert/jenkinsjson/convertTestFiles/fileOps/fileOpsCreate/Jenkinsfile
- convert/jenkinsjson/convertTestFiles/fileOps/fileOpsCreate/fileOpsCreate.yaml
- convert/jenkinsjson/convertTestFiles/fileOps/fileOpsCreate/fileOpsCreate_snippet.json
- convert/jenkinsjson/json/fileOperations.go
- convert/jenkinsjson/json/fileOperations_test.go
Added "FileCreateOperation " support to go
[fileCreateOperation.json](https://github.com/user-attachments/files/17213426/fileCreateOperation.json)
Output V0 yaml:
pipeline:
identifier: default
name: default
orgIdentifier: default
projectIdentifier: default
properties:
ci:
codebase:
build: <+input>
stages:
- stage:
identifier: build
name: build
spec:
cloneCodebase: true
execution:
steps:
- stepGroup:
identifier: Stage__null2771a5
name: Create File
steps:
- step:
identifier: fileoperations9b3c55
name: fileCreateOperation
spec:
command: echo 'Hello, World!' > newfile.txt
image: alpine
timeout: ""
type: Run
timeout: ""
platform:
arch: Amd64
os: Linux
runtime:
spec: {}
type: Cloud
type: CI
> feat: [CI-14420]: FileOps migration: FileCreateOperation support

- convert/harness/downgrader/downgrade.go
Error was in line - 585 of case "plugins/artifactory:latest" inside downgrade.go. Instead of sourcePath it should be source.
Sample yaml before downgrading - 
```yaml
version: 1
kind: pipeline
type: ""
name: ""
spec:
stages:
- desc: ""
id: build
name: build
strategy: null
delegate: []
status: null
type: ci
when: null
failure: null
inputs: {}
spec:
cache: null
clone: null
platform: null
runtime: null
steps:
- id: Stage__null6c2707
name: Build image
desc: ""
type: group
timeout: ""
strategy: null
when: null
failure: null
inputs: {}
spec:
steps: []
- id: Stage__null92ca9e
name: Push image to Artifactory
desc: ""
type: group
timeout: ""
strategy: null
when: null
failure: null
inputs: {}
spec:
steps:
- id: rtDockerPushf4ba5f
name: rtDockerPush
desc: ""
type: plugin
timeout: ""
strategy: null …
```
> fix: [CI-14643]: fixed error occuring while downgrading dockerPushStep and artifactUpload.

- convert/jenkinsjson/convert.go
Removed images references from the code and changed plugin step to run step.
NOTE: mergeRunSteps() is causing errors in maven, gradle and ant conversions, so these testings are done by commenting out that function.
Tried on 2.18.13-SNAPSHOT
Docs for the same - https://docs.google.com/document/d/1GlbwuHbwB9Ia6q6ZTDsxZ1Oss0Hj5KP-8dz3F-mOrSc/edit?usp=sharing
> fix: [CI-14766]: Converted maven, ant, gradle plugin step to run step from plugin step.

- convert/jenkinsjson/convert.go
- convert/jenkinsjson/convertTestFiles/nunit/Jenkinsfile
- convert/jenkinsjson/convertTestFiles/nunit/nunit.yaml
- convert/jenkinsjson/convertTestFiles/nunit/nunit_snippet.json
- convert/jenkinsjson/json/nunit.go
- convert/jenkinsjson/json/nunit_test.go
- samples/jenkins/Jenkinsfile
Nunit go-conversion:
Added "Nunit " support to go-convert specific to jenkins migration.
Nunit Jenkins Trace: [nunitTrace.json]
[nunitTrace.json](https://github.com/user-attachments/files/17381682/nunitTrace.json)
go run main.go jenkinsjson --downgrade ~/go/nunitTrace.json
Below is the resulted step in yaml:
```
- step:
identifier: nunit0d6d45
name: nunit
spec:
image: plugins/nunit
settings:
fail_if_no_results: 'true'
failed_tests_fail_build: 'true'
test_report_path: TestResult.xml
timeout: ''
type: Plugin
```
> nunit go-conversion

- convert/jenkinsjson/convert.go
- convert/jenkinsjson/convertTestFiles/jacoco/Jenkinsfile
- convert/jenkinsjson/convertTestFiles/jacoco/jacoco.json
- convert/jenkinsjson/convertTestFiles/jacoco/jacoco.yaml
- convert/jenkinsjson/json/convertStepUtil.go
- convert/jenkinsjson/json/jacoco.go
- convert/jenkinsjson/json/jacoco_test.go
- samples/jenkins/Jenkinsfile
Jaoco Conversion:
Added "jacoco" support to go-convert specific to Jenkins migration
Jacoco Jenkins Trace file:
[jacoco_jenkins_trace.json](https://github.com/user-attachments/files/17523136/jacoco_jenkins_trace.json)
Conversion command used:
go run main.go   jenkinsjson --downgrade <path_prefix>/Jacoco-JenkinsFile
Generated step as YAML
```yaml
- step:
identifier: jacoco66be31
name: jacoco
spec:
envVariables:
JAVA_HOME:
/Users/franciscojunior/.jenkins/tools/hudson.model.JDK/jdk8/zulu8.80.0.17-ca-jdk8.0.422-macosx_aarch64
M2_HOME:
/Users/franciscojunior/.jenkins/tools/hudson.tasks.Maven_MavenInstallation/M3
MAVEN_HOME:
/Users/franciscojunior/.jenkins/tools/hudson.tasks.Maven_MavenInstallation/M3
PATH+JDK:
/Users/franciscojunior/.jenkins/tools/hudson.model.JDK/jdk8/zulu8.80.0.17-ca-jdk8.0.4 …
```
> adding jacoco conversion step

- convert/jenkinsjson/convert.go
- convert/jenkinsjson/convertTestFiles/kubeCtl/Jenkinsfile
- convert/jenkinsjson/convertTestFiles/kubeCtl/kubeCtl.yaml
- convert/jenkinsjson/convertTestFiles/kubeCtl/kubeCtl_snippet.json
- convert/jenkinsjson/json/kubeCtl.go
- convert/jenkinsjson/json/kubeCtl_test.go
- samples/jenkins/Jenkinsfile
feat-kubectl: added the conversion for kube ctl
Trace File:
======
[kube__latest_with_all_fields.json](https://github.com/user-attachments/files/17595232/kube__latest_with_all_fields.json)
go run main.go jenkinsjson --downgrade "~/go/kube__latest_with_all_fields.json"
```
- step:
identifier: stagenulled0166
name: Apply Kubernetes Files
spec:
command: kubectl get pods
envVariables:
KUBE_CA_CERTIFICATE: ''
KUBE_CLUSTER: cluster-name
KUBE_CONTEXT: context-name
KUBE_CREDENTIALS_ID: credentialsId
KUBE_NAMESPACE: default
KUBE_SERVER: 'https://127.0.0.1:56227'
KUBE_TOKEN: <+secrets.getValue("kube_token")>
image: bitnami/kubectl
shell: Sh
timeout: null
```
> feat-kubectl: Added the conversion for kube-ctl

- command/jenkinsjson.go
- convert/jenkinsjson/convert.go
- convert/jenkinsjson/convert_test.go
- convert/jenkinsjson/option.go
Removed the pushed flag:
The pushed flag was unnecessary and potentially confusing
The logic now handles all cases without needing to track whether something was pushed
Simplified the loop logic:
Removed the conditional check if i != len(*steps)-1
Made the merge/no-merge decision more straightforward
Fixed the last step handling:
Always append the final cursor state after the loop
This ensures we don't lose any steps regardless of whether the last step was merged or not (which was the main issue).
Also added a function which checks that if image is non-default then it will not merge.
Jenkins pipeline which I mentioned in the ticket in now returning correct output.
```
pipeline:
identifier: default
name: default
orgIdentifier: default
projectIdentifier: default
properties:
ci:
codebase: …
```
> fix: [CI-14984]: Fixed mergeRunStep issue.

- convert/jenkinsjson/convert.go
This change adds handling for a `getContext` node we are seeing in a trace. There was two issues that this node was causing.
1. It broke parallel rendering for parallel step groups.
2. It caused all parallel steps to be produced with the same "getContext" name.
I'm not really sure what the `getContext` node is so as a result I'm not very confident that this is the best way to handle it.
Here is the getContext description from the trace file
> Get contextual object from internal APIs
My assumption is that the getContext node is added to the trace when Jenkins checks the conditional execution for a step which results in the step not running. Since the step never runs we don't get the step execution in the trace leaving only these mostly useless getContext nodes.
Jenkins stage
``` …
```
> fix: [CI-13903]: fix parallel steps for Consilio brutal pipeline

- convert/jenkinsjson/convert.go
- convert/jenkinsjson/convertTestFiles/mailer/Jenkinsfile
- convert/jenkinsjson/convertTestFiles/mailer/mailer.yaml
- convert/jenkinsjson/convertTestFiles/mailer/mailer_snippet.json
- convert/jenkinsjson/json/mailer.go
- convert/jenkinsjson/json/mailer_test.go
- samples/jenkins/Jenkinsfile
Mailer go-conversion:
Added "Mailer" support to go-convert specific to jenkins migration.
Mailer Jenkins Trace:
[Mailer_Trace.json](https://github.com/user-attachments/files/17787751/Mailer_Trace.json)
go run main.go jenkinsjson --downgrade ~/go/Mailer_Trace.json
Mailer harness pipeline step:
```
- step:
identifier: mail0fb620
name: Mailer
spec:
image: plugins/email
settings:
body:
"\n                    Build Status: FAILURE\n                    Check
console output at: http://localhost:8080/job/Mail_Pipeline/15/console\n
\                   "
from.address: <from_address>
host: smtp.gmail.com
password: <password>
port: "587"
recipients: test.user@testmail.com
subject: "Jenkins Build - Mail_Pipeline #15"
username: <username>
timeout: ""
type: Plugin
```
> feat-mailer: Added Mailer Plugin Conversion

- convert/jenkinsjson/convert.go
- convert/jenkinsjson/convertTestFiles/javadoc/Jenkinsfile
- convert/jenkinsjson/convertTestFiles/javadoc/javadoc.yml
- convert/jenkinsjson/convertTestFiles/javadoc/javadocSnippet.json
- convert/jenkinsjson/json/javadoc.go
- convert/jenkinsjson/json/javadoc_test.go
- samples/jenkins/Jenkinsfile
Added "Javadoc" support to go-convert specific to jenkins migration.
[op-javadoc.json](https://github.com/user-attachments/files/17545293/op-javadoc-without-dir__1.json)
```bash
go run main.go jenkinsjson -downgrade ~/Downloads/op-javadoc.json 
```
<details>
<summary>Example Harness v0 YAML</summary>
```yaml
pipeline:
identifier: default
name: default
orgIdentifier: default
projectIdentifier: default
properties:
ci:
codebase:
build: <+input>
stages:
- stage:
identifier: build
name: build
spec:
cloneCodebase: true
execution:
steps:
- stepGroup:
identifier: Stage__nullb5a696
name: Checkout
timeout: ""
- stepGroup:
identifier: Stage__nullcbb8ae
name: Build
steps:
- step:
identifier: sh574fb7
name: sh
spec:
command: cd complete && gradle clean build --info --stacktrace
image: alpine
shell: Sh …
```
> feat: [CI-14710]: Javadoc Conversion Logic

- convert/jenkinsjson/convert.go
- convert/jenkinsjson/convertTestFiles/nodejs/Jenkinsfile
- convert/jenkinsjson/convertTestFiles/nodejs/nodejs.yaml
- convert/jenkinsjson/convertTestFiles/nodejs/nodejs_snippet.json
- convert/jenkinsjson/json/nodejs.go
- convert/jenkinsjson/json/nodejs_test.go
- samples/jenkins/Jenkinsfile
Nodejs go-conversion:
Added "Nodejs" support to go-convert specific to jenkins migration.
Nodejs Jenkins Trace:
[Test_Nodejs_plugin__4.json](https://github.com/user-attachments/files/17822886/Test_Nodejs_plugin__4.json)
go run main.go jenkinsjson --downgrade ~/go/Test_Nodejs_plugin__4.json
Harness Nodejs test pipeline [here](https://app.harness.io/ng/account/gCoPSwHxS7ipOgx2iA9tOQ/module/ci/orgs/default/projects/jenkinstoharness/pipelines/Vani_Nodejs/deployments/7xFIHcf4Qnqo266DMu44kQ/pipeline?storeType=INLINE).
Nodejs harness pipeline step:
```
- step:
identifier: stagenull99086b
name: Nodejs
spec:
command: |
npm --version
npm install
image: node:latest
shell: Sh
timeout: ""
type: Run
```
> Feat nodejs: Added Nodejs Conversion

- command/jenkinsjson.go
- convert/harness/downgrader/downgrade.go
- convert/harness/downgrader/option.go
- convert/jenkinsjson/convert.go
- convert/jenkinsjson/convert_test.go
- convert/jenkinsjson/json/bat.go
- convert/jenkinsjson/json/bat_test.go
- convert/jenkinsjson/json/powershell.go
- convert/jenkinsjson/json/powershell_test.go
- convert/jenkinsjson/option.go
I'm not confident that this is the best solution here so please let me know if you disagree with this change.
The issue I am trying to solve here is that most steps in the jenkinsjson converter do not provide a default image. This breaks the import into Harness when using Kubernetes infra as it requires a step image. 
I started this change by tracking down each place where my trace was outputting a step with no image and adding the default image logic into the step conversion. After doing 2 or 3 of these I realised that I would need to add the default image logic to every step creation, of which there is many. Which brought me to this conclusion, why not default the image in the downgrader is none was specified during the conversion. Simple right?
As I am typing this, I realise I could …
> fix: [CI-13903]: move default image logic to downgrader

- convert/jenkinsjson/convert.go
- convert/jenkinsjson/convertTestFiles/unarchive/Jenkinsfile
- convert/jenkinsjson/convertTestFiles/unarchive/unarchive.yaml
- convert/jenkinsjson/convertTestFiles/unarchive/unarchive_snippet.json
- convert/jenkinsjson/json/unarchive.go
- convert/jenkinsjson/json/unarchive_test.go
- samples/jenkins/Jenkinsfile
Unarchive go-conversion:
Added "Unarchive" support to go-convert specific to jenkins migration.
Unarchive Jenkins Trace:
[Vani_Unarchive.json](https://github.com/user-attachments/files/17896508/Vani_Unarchive.json)
go run main.go jenkinsjson --downgrade ~/go/Vani_Unarchive.json
Unarchive harness pipeline step:
```
- step:
identifier: unarchive4bf5e3
name: Unarchive
spec:
image: plugins/archive
settings:
action: extract
exclude: ''
format: zip
glob: '**/*'
overwrite: 'true'
source: archive.zip
target: unarchived_files/zip/
```
Unarchive Harness Pipeline [here](https://app.harness.io/ng/account/gCoPSwHxS7ipOgx2iA9tOQ/module/ci/orgs/default/projects/jenkinstoharness/pipelines/Vani_Unarchive_Pipeline/deployments/gmEez38qT1SQjBauDCS_6A/pipeline?storeType=INLINE)
> feat-unacrchive: Added a unarchive conversion step

- convert/harness/downgrader/downgrade.go
- convert/jenkinsjson/convert.go
- convert/jenkinsjson/json/deletedir.go
- convert/jenkinsjson/json/util.go
- convert/jenkinsjson/json/util_test.go
- convert/jenkinsjson/json/withCredentials.go
- convert/jenkinsjson/json/withCredentials_test.go
This PR includes a few changes,
1. Recurse into children for ws, dir and withCred step types
2. Add default child recurse for other unknown types
3. Derive pipeline ID from name
4. Ignore ansiColor plugin steps
> fix: [CI-15388]: recurse into chilren for ws, dir and withCred steps

- command/jenkinsjson.go
- convert/jenkinsjson/convert.go
This PR adds "bulk" or directory based conversion of Jenkins trace files.
By providing a directory as the input rather than a file the tool will walk the filesystem from that root converting all JSON files it finds.
Also added an --output-dir option so that converted yaml files can be saved to disc rather than printing all to STDOUT
> fix: [CI-15419]: enable bulk conversion of traces with dir

- convert/jenkinsjson/convert.go
- convert/jenkinsjson/convertTestFiles/Notification/Jenkinsfile
- convert/jenkinsjson/convertTestFiles/Notification/notification.yaml
- convert/jenkinsjson/convertTestFiles/Notification/notification_snippet.json
- convert/jenkinsjson/json/notification.go
- convert/jenkinsjson/json/notification_test.go
- samples/jenkins/Jenkinsfile
Notification go-conversion:
Added "Notification" support to go-convert specific to jenkins migration.
Norification Jenkins Trace:
[notification_28.json](https://github.com/user-attachments/files/18118924/notification_28.json)
go run main.go jenkinsjson --downgrade ~/go/notification_28.json
Harness Notification Pipeline is [here](https://app.harness.io/ng/account/gCoPSwHxS7ipOgx2iA9tOQ/module/ci/orgs/default/projects/jenkinstoharness/pipelines/Vani_Notification/executions/bFVDXNsrQXmpeYWMwmdAuQ/pipeline).
Notification harness pipeline step:
```
- step:
identifier: notifyendpointsaa7206
name: Notification
spec:
image: plugins/webhook
settings:
content-type: application/json
method: POST
template: |-
{
"status": "SUCCESSFUL",
"notes": "Build metrics for analysis"
}
token-value: <+input> …
```
> feat-notification: Notification conversion step for harness

- convert/jenkinsjson/convert.go
- convert/jenkinsjson/convertTestFiles/artifactUploadJfrog/artifactuploadSnippet.json
- convert/jenkinsjson/convert_test.go
- convert/jenkinsjson/json/artifactUploadJfrog.go
- convert/jenkinsjson/json/artifactUploadJfrog_test.go
Compiled trace files include both `parameterMap` and `harness-attributes` which tell this tool the type of step to generate.  
Both of these fields are now completely aligned, and contain essentially duplicate data.  In the tool, the `harness-attibutes` was being used for `artifactoryUpload` and `tool` types.  
This PR changes both of those steps to use `parameterMap` 
- Reduce duplication
- Adding features to upstream trace generator easier, as does not require parity for generating both fields. 
- Updated unit tests
- Manual testing with trace files that contain both step types.
> CI-15185 Use `parameterMap` for `artifactoryUpload` and `tools` 

- convert/jenkinsjson/convert.go
- convert/jenkinsjson/json/sh.go
Adds checks to not merge `sh` steps if they have a unified trace label
These belong to differente executions and are not logically related, so we should not merge them
Manual
> Ci 15185 Unified trace: handle branched sh

- command/jenkinsjson.go
- convert/jenkinsjson/convert.go
- convert/jenkinsjson/convert_test.go
- convert/jenkinsjson/option.go
Add support for configuring infrastructure options in the Jenkins to Harness YAML converter.
Changes:
- Add CLI flags:
- `--infrastructure`: cloud (default), kubernetes, shell
- `--os`: linux, windows, macos
- `--arch`: amd64, arm64
- Add platform configuration:
- OS and architecture settings
- Normalize OS names (linux, windows, macos)
- Add runtime configuration:
- cloud: Default cloud runtime
- kubernetes: Kubernetes runtime
- shell: Local shell runtime
- Add validation for all options
- Maintain backward compatibility with existing behavior
> feat: [CI-16470]: Support for configuring infrastructure options in the JenkinsJson to Harness YAML (V1) converter

- convert/harness/downgrader/downgrade.go
- convert/jenkinsjson/convert.go
This will be handled on both sides. Some pipelines are created with empty steps. Adding in null check to early return in that case
> fix: [CI-16589]: Attempt to handle merge null ptr exception

- convert/jenkinsjson/convert.go
- convert/jenkinsjson/convertTestFiles/testResultsAggregator/Jenkinsfile
- convert/jenkinsjson/convertTestFiles/testResultsAggregator/testResultsAggregator_test.json
- convert/jenkinsjson/convertTestFiles/testResultsAggregator/testResultsAggregator_test.yaml
- convert/jenkinsjson/json/testResultsAggregator.go
- convert/jenkinsjson/json/testResultsAggregator_test.go
- samples/jenkins/Jenkinsfile
Complete trace file json
[test-results-aggregator-trace.json](https://github.com/user-attachments/files/19095332/test-results-aggregator-trace.json)
converted yaml
```yaml
- step:
identifier: testresultsaggregator01c08d
name: testResultsAggregator
spec:
image: plugins/test-results-aggregator
settings:
group: <+input>
include_pattern: <+input>
reports_dir: <+input>
tool: <+input>
timeout: ""
type: Plugin
```
> feat: [CI-15022]: adding go convert logic for testResultsAggregator
