drone/go-convert

convert/harness/downgrader/downgrade.go
convert/harness/downgrader/testdata/example-4.yaml
convert/harness/downgrader/testdata/example-4.yaml.golden

this improves downgraded JEXL conditions, but there is still more work to be done

(fix) better JEXL conditions

---

command/drone.go
convert/drone/convert.go
convert/drone/option.go

ability to pass into CLI organisation secrets IDS which need promoted to have the org. prefix in pipeline.

(bug) organization secrets require "org." prefix

---

convert/harness/downgrader/downgrade.go
convert/harness/downgrader/testdata/example-11.yaml
convert/harness/downgrader/testdata/example-11.yaml.golden
convert/harness/yaml/step.go

v0 yaml supports `envVariables` for plugin steps

bug: env variables in downgraded plugin steps

---

convert/harness/downgrader/downgrade.go
convert/harness/downgrader/testdata/example-13.yaml
convert/harness/downgrader/testdata/example-13.yaml.golden
convert/harness/downgrader/yaml/parse.go

If two pipelines weren't present, only was getting shown.

(bug) fixes issue where two pipelines weren't getting downgraded

---

convert/harness/downgrader/testdata/example-15.yaml.golden

separate change broke this test

tests: fix downgrader example-15 test

---

convert/harness/downgrader/downgrade.go
convert/harness/downgrader/testdata/stage-stragegy-matrix.yaml
convert/harness/downgrader/testdata/stage-stragegy-matrix.yaml.golden
convert/harness/downgrader/testdata/strategy-matrix-step.yaml
convert/harness/downgrader/testdata/strategy-matrix-step.yaml.golden
convert/harness/yaml/step.go

adding tests for step and stage matrix pipelines

feat: downgrade step matrix support

---

convert/gitlab/convert.go
convert/gitlab/testdata/matrix/matrix.yaml.golden

gitlab matrix axes become environment variables, this change maintains that behavior

feat: gitlab matrix step env vars

---

convert/harness/downgrader/downgrade.go
convert/harness/downgrader/testdata/example-17.yaml
convert/harness/downgrader/testdata/example-17.yaml.golden
convert/harness/yaml/step.go

This will automatically downgrade a v1 plugin step which uses kaniko-docker to a v0 BuildAndPushDocker step

[feat]: [CI-11166]: Convert V1 Plugin to V0 DockerHub

---

convert/jenkinsjson/convertTestFiles/verifySha256/Jenkinsfile
convert/jenkinsjson/convertTestFiles/verifySha256/verifySha256.yaml
convert/jenkinsjson/convertTestFiles/verifySha256/verifySha256Snippet.json
convert/jenkinsjson/covert.go
convert/jenkinsjson/json/verifySha256.go
convert/jenkinsjson/json/verifySha256_test.go

- VerifySHA256 utility function and its unit test & other related files

VerifySHA256 utility step

---

convert/jenkinsjson/convertTestFiles/verifySha1/Jenkinsfile
convert/jenkinsjson/convertTestFiles/verifySha1/verifySha1.yaml
convert/jenkinsjson/convertTestFiles/verifySha1/verifySha1Snippet.json
convert/jenkinsjson/covert.go
convert/jenkinsjson/json/verifySha1.go
convert/jenkinsjson/json/verifySha1_test.go

- VerifySHA1 utility function and its unit test & other related files

VerifySHA1 utility step

---

convert/jenkinsjson/convertTestFiles/sha256/JenkinsFile
convert/jenkinsjson/convertTestFiles/sha256/sha256.yaml
convert/jenkinsjson/convertTestFiles/sha256/sha256Snippet.json
convert/jenkinsjson/covert.go
convert/jenkinsjson/json/sha256.go
convert/jenkinsjson/json/sha256_test.go

- SHA256 utility function and its unit test & other related files

SHA256 utility step

---

convert/jenkinsjson/convertTestFiles/sha1/JenkinsFile
convert/jenkinsjson/convertTestFiles/sha1/sha1.yaml
convert/jenkinsjson/convertTestFiles/sha1/sha1Snippet.json
convert/jenkinsjson/covert.go
convert/jenkinsjson/json/sha1.go
convert/jenkinsjson/json/sha1_test.go
convert/jenkinsjson/json/withDockerContainer_test.go

- SHA1 utility function and its unit test & other related files
- fmted

SHA1 utility step

---

convert/jenkinsjson/convert.go
convert/jenkinsjson/convertTestFiles/powershell/Jenkinsfile
convert/jenkinsjson/convertTestFiles/powershell/powershell.yaml
convert/jenkinsjson/convertTestFiles/powershell/powershellSnippet.json
convert/jenkinsjson/json/powershell.go
convert/jenkinsjson/json/powershell_test.go
samples/jenkins/Jenkinsfile
samples/jenkins/Jenkinsfile_win

Converter for the powershell Jenkins function

feat: CI-14181 Jenkins powershell function

---

convert/jenkinsjson/convert.go

- merge `run` steps in same `stepGroup` 
- added a function to go through the run step at each recursive call of `collectStepsWithID`

feat: [CI-13994] : Merge sh/run steps if images and other things did not change

---

.gitignore
convert/jenkinsjson/convert.go
convert/jenkinsjson/convertTestFiles/httpRequest/Jenkinsfile
convert/jenkinsjson/convertTestFiles/httpRequest/httpRequest.json
convert/jenkinsjson/convertTestFiles/httpRequest/httpRequest.yaml
convert/jenkinsjson/json/convertStepUtil.go
convert/jenkinsjson/json/httpRequest.go
convert/jenkinsjson/json/httpRequest_test.go

Http plugin changes 

---

convert/jenkinsjson/convert.go
convert/jenkinsjson/convertTestFiles/cobertura/Jenkinsfile
convert/jenkinsjson/convertTestFiles/cobertura/cobertura.json
convert/jenkinsjson/convertTestFiles/cobertura/cobertura.yaml
convert/jenkinsjson/json/cobertura.go
convert/jenkinsjson/json/cobertura_test.go
convert/jenkinsjson/json/convertStepUtil.go
samples/jenkins/Jenkinsfile

Added go convert logic for cobertura coverage jenkins pipeline compatibility support
Test cases added and passed.
Sample files for yaml, trace json, jenkins added in respective directories.

Cobertura go convert changes

---

convert/jenkinsjson/convert.go
convert/jenkinsjson/convertTestFiles/publishHTML/Jenkinsfile
convert/jenkinsjson/convertTestFiles/publishHTML/publishHTML.json
convert/jenkinsjson/convertTestFiles/publishHTML/publishHTML.yaml
convert/jenkinsjson/json/publishHTML.go
convert/jenkinsjson/json/publishHTML_test.go
convert/jenkinsjson/json/publishHtml.go
samples/jenkins/Jenkinsfile

Added code changes for publishHTML plugin support
[htmlPublish-full-trace.json](https://github.com/user-attachments/files/17749306/htmlPublish-full-trace.json)

publishHTML plugin support

---

convert/jenkinsjson/convert.go
convert/jenkinsjson/convertTestFiles/nexusArtifactUploader/Jenkinsfile
convert/jenkinsjson/convertTestFiles/nexusArtifactUploader/nexusArtifactUploader.json
convert/jenkinsjson/convertTestFiles/nexusArtifactUploader/nexusArtifactUploader.yaml
convert/jenkinsjson/json/nexusArtifactUploader.go
convert/jenkinsjson/json/nexusArtifactUploader_test.go
samples/jenkins/Jenkinsfile

Go convert changes for nexus artifact uploader
Complete trace file
[senthil-nexus-artifact-uploader__2.json](https://github.com/user-attachments/files/17870898/senthil-nexus-artifact-uploader__2.json)
Jenkins execution link 
http://3.25.193.140:8080/job/senthil-nexus-artifact-uploader/2/
Generated output
- step:
identifier: nexusartifactuploadera3af28
name: nexusArtifactUploader
spec:
image: harnesscommunity/drone-nexus-publish
settings:
artifacts: '[{"artifactId":"fruit-names-v0.1","classifier":"","file":"fruit_names.txt","type":"txt"}]'
group_id: test01
nexus_version: nexus3
password: add password
protocol: http
repository: senthilmaven2
server_url: 43.204.190.241:8081/
username: add user name

Nexus artifact senthil 02

---

convert/jenkinsjson/convert.go
convert/jenkinsjson/convertTestFiles/slackSend/slackSend.json
convert/jenkinsjson/convertTestFiles/slackSend/slackSend.yaml
convert/jenkinsjson/convertTestFiles/slackUserIdFromEmail/Jenkinsfile
convert/jenkinsjson/convertTestFiles/slackUserIdFromEmail/slackUserIdFromEmailSnippet.json
convert/jenkinsjson/convertTestFiles/slackUserIdFromEmail/slackUserIdFromEmailSnippet.yaml
convert/jenkinsjson/convertTestFiles/slackUserIdsFromCommitters/Jenkinsfile
convert/jenkinsjson/convertTestFiles/slackUserIdsFromCommitters/slackUserIdsFromCommitters.yaml
convert/jenkinsjson/convertTestFiles/slackUserIdsFromCommitters/slackUserIdsFromCommittersSnippet.json
convert/jenkinsjson/json/slackSend.go
convert/jenkinsjson/json/slackSend_test.go
convert/jenkinsjson/json/slackUserIdFromEmail.go
convert/jenkinsjson/json/slackUserIdFromEmail_test.go
convert/jenkinsjson/json/slackUserIdsFromCommitters.go
convert/jenkinsjson/json/slackUserIdsFromCommitters_test.go
samples/jenkins/Jenkinsfile

go convert for slackUserIdFromEmail and slackUserIdsFromCommitters
[slackUserIdsFromCommitters_senthil_01.json](https://github.com/user-attachments/files/18078345/slackUserIdsFromCommitters_senthil_01.json)
converted yaml:
```yaml - step:
identifier: slackuseridsfromcommitters0bf200
name: slackUserIdsFromCommitters
spec:
image: plugins/slack
settings:
access_token: <+input>
committers_slack_id: "true"
git_repo_path: <+input>
timeout: ""
type: Plugin```

Slack get ids 03

---

convert/jenkinsjson/convert.go
convert/jenkinsjson/convertTestFiles/artifactoryRtCommands/JenkinsFile.publishBuildInfo
convert/jenkinsjson/convertTestFiles/artifactoryRtCommands/JenkinsFile.rtDownload
convert/jenkinsjson/convertTestFiles/artifactoryRtCommands/JenkinsFile.rtGradleRun
convert/jenkinsjson/convertTestFiles/artifactoryRtCommands/JenkinsFile.rtMavenRun
convert/jenkinsjson/convertTestFiles/artifactoryRtCommands/JenkinsFile.rtPromote
convert/jenkinsjson/convertTestFiles/artifactoryRtCommands/JenkinsFile.xrayScan
convert/jenkinsjson/convertTestFiles/artifactoryRtCommands/publishBuildInfo.json
convert/jenkinsjson/convertTestFiles/artifactoryRtCommands/publishBuildInfo.yaml
convert/jenkinsjson/convertTestFiles/artifactoryRtCommands/rtDownload.json
convert/jenkinsjson/convertTestFiles/artifactoryRtCommands/rtDownload.yaml
convert/jenkinsjson/convertTestFiles/artifactoryRtCommands/rtGradleRun.json
convert/jenkinsjson/convertTestFiles/artifactoryRtCommands/rtGradleRun.yaml
convert/jenkinsjson/convertTestFiles/artifactoryRtCommands/rtMavenRun.json
convert/jenkinsjson/convertTestFiles/artifactoryRtCommands/rtMavenRun.yaml
convert/jenkinsjson/convertTestFiles/artifactoryRtCommands/rtPromote.json
convert/jenkinsjson/convertTestFiles/artifactoryRtCommands/rtPromote.yaml
convert/jenkinsjson/convertTestFiles/artifactoryRtCommands/xrayScan.json
convert/jenkinsjson/convertTestFiles/artifactoryRtCommands/xrayScan.yaml
convert/jenkinsjson/json/artifactoryRtCommands.go
convert/jenkinsjson/json/artifactoryRtCommands_test.go
samples/jenkins/Jenkinsfile

feat: [CI -15024] - Add rt Commands support
[artifactory_trace.zip](https://github.com/user-attachments/files/18959903/artifactory_trace.zip)
rtDownload.json
- step:
identifier: rtdownload22c8b2
name: rtDownload
spec:
image: plugins/artifactory
settings:
access_token: <+input>
build_name: <+input>
build_number: <+input>
command: download
module: <+input>
project: <+input>
spec_path: <+input>
url: <+input>
username: <+input>
rtMavenRun.json
- step:
identifier: rtmavenrundac366
name: rtMavenRun
spec:
image: plugins/artifactory
settings:
access_token: <+input>
build_name: <+input>
build_number: <+input>
build_tool: mvn
deployer_id: <+input>
goals: clean install
resolve_release_repo: <+input>
resolve_snapshot_repo: <+input>
resolver_id: <+input>
source: pom.xml
url: <+input>
username: …

feat: [CI -15024]: Add rt Commands support
